[project]
name = "lang-trm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "einops>=0.8.1",
    "mlflow>=3.6.0",
    "torch>=2.9.1",
    "transformers>=4.57.3",
]
